### ISSUE TITLE
Vnu Task List

### ISSUE THREAD

**Issue by vnu** [WomenWhoCode/WomenWhoCodeSwift#129]
#### Chat
- [ ] Add slack channel id to topics #67 
- [x] Populate Chat Channels with some data based on features
- [x]  Populate channel Ids in Parse for the generated slack channels
- [ ] Show @mentions and #channel
- [ ] Show list of categories
- [ ] Ability to send messages
- [ ] Infinite loading and pull to refresh
- [ ] Ability to get new messages
- [ ] Search for channels and members
- [ ] Persisting members

#### Events
- [ ] Meetup Deep Link - ability to RSVP
- [ ] Event Map view
- [ ] Populate Parse with events
- [ ] Use the right events for Event Details Page
- [ ] Populate User Profile
- [ ] Polish Event List page a little bit
