### ISSUE TITLE
Maha Task List

### ISSUE THREAD

**Issue by vnu** [WomenWhoCode/WomenWhoCodeSwift#130]
- [ ] Setting / Preference #8  
Profile Page 
- [ ] Add Constraints 
- [ ] Add correct awesome icon  
- [ ] Add Following button
- [ ] Remove segmented control 
- [ ] Add animation  
Topics
- [ ] Add topic details
