### ISSUE TITLE
Prasanthi Task List

### ISSUE THREAD

**Issue by vnu** [WomenWhoCode/WomenWhoCodeSwift#131]
- [x] Update EventsPage depending on filter settings #89 
- [x]  Clicking on subscribe button for topic should move it into the subscribed list #125 
- [x] Infinite Scrolling for Event List #132 
- [x] Added newsletters to Parse DB

**Comment by mahagovind** [comment]
Closed the other issues , just update this list .
